name: ci
on:
  push:
    branches:
     - 'main'
  pull_request:
jobs:
  static:
    runs-on: ubuntu-latest
    name: "CI"
    steps:
    - uses: actions/checkout@v2
    - name: Play with shell
      run: |
        echo 'Hello!'
        echo "That's it."
        exit 1
