name: ci
on: [push, pull_request]
jobs:
  static:
    runs-on: ubuntu-latest
    name: "CI"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        echo 'test'
